[package]
name = "cs2_dumper_generated_rs"
version = "2.0.14019"
edition = "2021"
readme = "README.md"
repository = "https://github.com/mccadecortez/cs2-dumper-generated-rs"
license = "MIT"

[lib]
path = "generated.rs"

[profile.release]
overflow-checks = true

[profile.dev]
overflow-checks = true