name: Generator
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run
        run: ./update.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
