name: Generator
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      # FIXME: ensure submodule has all commits
      - name: Update submodules
        run: git submodule update --init --recursive

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run
        run: ./update.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
